const data = {
  items: [
    {
      code: "0001",
      name: "SAMSUNG ADOPTER 25W charger",
      quantity: 5,
      purchasePrice: 550,
      salePrice: 1250,
    },
    {
      code: "0002",
      name: "Iphone adopter 25W charger 3pin",
      quantity: 1,
      purchasePrice: 750,
      salePrice: 2000,
    },
    {
      code: "0003",
      name: "Ronin R29 handfree smartphone",
      quantity: 6,
      purchasePrice: 350,
      salePrice: 795,
    },
    {
      code: "0004",
      name: "Ronin R9 handfree smartphone",
      quantity: 6,
      purchasePrice: 460,
      salePrice: 995,
    },
    {
      code: "0005",
      name: "Faster F15 handfree",
      quantity: 3,
      purchasePrice: 238,
      salePrice: 450,
    },
    {
      code: "0006",
      name: "Faster F9 handree",
      quantity: 3,
      purchasePrice: 268,
      salePrice: 550,
    },
    {
      code: "0007",
      name: "mobile back skin 3d sheet",
      quantity: 111,
      purchasePrice: 125,
      salePrice: 500,
    },
    {
      code: "0008",
      name: "Faster TG-330 Neckband",
      quantity: 2,
      purchasePrice: 2350,
      salePrice: 3500,
    },
    {
      code: "0009",
      name: "Ronin R-970 Neckband wireless headphones",
      quantity: 2,
      purchasePrice: 1900,
      salePrice: 3000,
    },
    {
      code: "0010",
      name: "privacy mate sheet front screen",
      quantity: 5,
      purchasePrice: 290,
      salePrice: 650,
    },
    {
      code: "0011",
      name: "Clear Privacy sheet front screen",
      quantity: 5,
      purchasePrice: 290,
      salePrice: 650,
    },
    {
      code: "0012",
      name: "mate front screen sheet hydrogel",
      quantity: 10,
      purchasePrice: 120,
      salePrice: 300,
    },
    {
      code: "0013",
      name: "HD front screen sheet hydrogel",
      quantity: 10,
      purchasePrice: 120,
      salePrice: 300,
    },
    {
      code: "0014",
      name: "OPPO adopter 67W charger",
      quantity: 6,
      purchasePrice: 340,
      salePrice: 850,
    },
    {
      code: "0015",
      name: "Vivo adopter 67W charger",
      quantity: 6,
      purchasePrice: 340,
      salePrice: 850,
    },
    {
      code: "0016",
      name: "One Plus data cable",
      quantity: 10,
      purchasePrice: 100,
      salePrice: 300,
    },
    {
      code: "0017",
      name: "Gionee handree",
      quantity: 10,
      purchasePrice: 120,
      salePrice: 300,
    },
    {
      code: "0018",
      name: "mix media boofer voofer handree",
      quantity: 20,
      purchasePrice: 130,
      salePrice: 450,
    },
    {
      code: "0019",
      name: "BMT handfree",
      quantity: 12,
      purchasePrice: 130,
      salePrice: 450,
    },
    {
      code: "0020",
      name: "OTG pin Type-C ",
      quantity: 10,
      purchasePrice: 15,
      salePrice: 100,
    },
    {
      code: "0021",
      name: "anywarshy handree",
      quantity: 1,
      purchasePrice: 220,
      salePrice: 500,
    },
    {
      code: "0022",
      name: "Card Reader",
      quantity: 30,
      purchasePrice: 10,
      salePrice: 100,
    },
    {
      code: "0023",
      name: "Finzu Cable fast charging 6A",
      quantity: 10,
      purchasePrice: 75,
      salePrice: 250,
    },
    {
      code: "0024",
      name: "Iphone 60 type-C Cable",
      quantity: 5,
      purchasePrice: 130,
      salePrice: 350,
    },
    {
      code: "0025",
      name: "Poxsoon",
      quantity: 5,
      purchasePrice: 65,
      salePrice: 200,
    },
    {
      code: "0026",
      name: "Vatnam Handfree boofer",
      quantity: 10,
      purchasePrice: 85,
      salePrice: 300,
    },
    {
      code: "0027",
      name: "Sim ejector pin",
      quantity: 100,
      purchasePrice: 1,
      salePrice: 20,
    },
    {
      code: "0028",
      name: "Mi6 Adopter fast charger",
      quantity: 3,
      purchasePrice: 250,
      salePrice: 600,
    },
    {
      code: "0029",
      name: "Super ASUS Adopter fast charger",
      quantity: 6,
      purchasePrice: 260,
      salePrice: 750,
    },
    {
      code: "0030",
      name: "Iphone 20W adopter fast cahrging 2pin",
      quantity: 1,
      purchasePrice: 550,
      salePrice: 2000,
    },
    {
      code: "0031",
      name: "A9 ANC touch screen earbuds white",
      quantity: 1,
      purchasePrice: 1750,
      salePrice: 4250,
    },
    {
      code: "0032",
      name: "A9 ANC touch screen earbuds black",
      quantity: 1,
      purchasePrice: 1850,
      salePrice: 4500,
    },
    {
      code: "0033",
      name: "Infinix Hot 30i smartphone 8/128",
      quantity: 1,
      purchasePrice: 25500,
      salePrice: 28000,
    },
    {
      code: "0034",
      name: "itel 2165 button mobile",
      quantity: 1,
      purchasePrice: 2100,
      salePrice: 2750,
    },
    {
      code: "0035",
      name: "itel 2166 button mobile",
      quantity: 1,
      purchasePrice: 2420,
      salePrice: 3150,
    },
    {
      code: "0036",
      name: "itel 5262 button mobile",
      quantity: 1,
      purchasePrice: 3534,
      salePrice: 4150,
    },
    {
      code: "0037",
      name: "itel music 430 button mobile",
      quantity: 1,
      purchasePrice: 3350,
      salePrice: 4000,
    },
    {
      code: "0038",
      name: "itel musik 400 button mobile",
      quantity: 1,
      purchasePrice: 4400,
      salePrice: 5000,
    },
    {
      code: "0039",
      name: "Nokia 105 Classec button mobile",
      quantity: 1,
      purchasePrice: 3550,
      salePrice: 4150,
    },
    {
      code: "0040",
      name: "Nokia 106 button mobile",
      quantity: 1,
      purchasePrice: 4330,
      salePrice: 5000,
    },

    {
      code: "0041",
      name: "L002 Mp3 Speakers",
      quantity: 1,
      purchasePrice: 800,
      salePrice: 1750,
    },
    {
      code: "0042",
      name: "Airpods Pro iPhone",
      quantity: 1,
      purchasePrice: 1450,
      salePrice: 3050,
    },
    {
      code: "0043",
      name: "Mobile Wall Stand",
      quantity: 5,
      purchasePrice: 14,
      salePrice: 70,
    },
    {
      code: "0044",
      name: "Oppo 2A MicroUSB Cable",
      quantity: 6,
      purchasePrice: 45,
      salePrice: 250,
    },
    {
      code: "0045",
      name: "380A/3301 Tripod Stand",
      quantity: 1,
      purchasePrice: 1250,
      salePrice: 2650,
    },
    {
      code: "0046",
      name: "P9 Pro Max Headphones",
      quantity: 1,
      purchasePrice: 1150,
      salePrice: 2450,
    },
    {
      code: "0047",
      name: "M10 DAMIX Wireless earbuds V5.3",
      quantity: 1,
      purchasePrice: 580,
      salePrice: 900,
    },
    {
      code: "0048",
      name: "Gionee Type Handsfree Lott",
      quantity: 2,
      purchasePrice: 360,
      salePrice: 650,
    },
    {
      code: "0049",
      name: "1.5m USB Extension Cable",
      quantity: 2,
      purchasePrice: 100,
      salePrice: 350,
    },
    {
      code: "0050",
      name: "Wireless Charger Watch",
      quantity: 2,
      purchasePrice: 140,
      salePrice: 450,
    },
    {
      code: "0051",
      name: "Foxcon iPhone Lightening Cable",
      quantity: 2,
      purchasePrice: 65,
      salePrice: 300,
    },
    {
      code: "0052",
      name: "Multicharger (Dadu Charger) Premium",
      quantity: 1,
      purchasePrice: 140,
      salePrice: 450,
    },
    {
      code: "0053",
      name: "Flash USB 16 GB Packing (Brand 3 Months Warranty)",
      quantity: 1,
      purchasePrice: 450,
      salePrice: 1150,
    },
    {
      code: "0054",
      name: "Flash USB 32 GB Packing (Brand 3 Months Warranty)",
      quantity: 1,
      purchasePrice: 560,
      salePrice: 1350,
    },
    {
      code: "0055",
      name: "Flash USB 64 GB Packing (Brand 3 Months Warranty)",
      quantity: 1,
      purchasePrice: 680,
      salePrice: 1850,
    },
    {
      code: "0056",
      name: "M16 Single Bluetooth",
      quantity: 1,
      purchasePrice: 265,
      salePrice: 680,
    },
    {
      code: "0057",
      name: "CC150 Single 2.4A Car Charger Space (Brand Warranty 1 Year)",
      quantity: 1,
      purchasePrice: 650,
      salePrice: 1450,
    },
    {
      code: "0058",
      name: "OTG iPhone Lott",
      quantity: 1,
      purchasePrice: 340,
      salePrice: 600,
    },
    {
      code: "0059",
      name: "8600 Charger TLG Lightchanger",
      quantity: 6,
      purchasePrice: 130,
      salePrice: 450,
    },
    {
      code: "0060",
      name: "Typel to 3.5 Samsung Single Connector",
      quantity: 1,
      purchasePrice: 150,
      salePrice: 450,
    },
    {
      code: "0061",
      name: "OTG Cable Type-C + MicroUSB",
      quantity: 1,
      purchasePrice: 95,
      salePrice: 350,
    },
    {
      code: "0062",
      name: "iPhone PD 20W Premium cable",
      quantity: 1,
      purchasePrice: 300,
      salePrice: 800,
    },
    {
      code: "0063",
      name: "Speedo 5C Battery Noklis",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 480,
    },
    {
      code: "0064",
      name: "4 GB MMC memory card",
      quantity: 1,
      purchasePrice: 255,
      salePrice: 550,
    },
    {
      code: "0065",
      name: "8 GB MMC Memory Card",
      quantity: 1,
      purchasePrice: 260,
      salePrice: 750,
    },
    {
      code: "0066",
      name: "16 GB MMC Memory Card",
      quantity: 1,
      purchasePrice: 350,
      salePrice: 1050,
    },
    {
      code: "0067",
      name: "EVO Card 64 GB Memory Card (Brand Warranty 3 Months)",
      quantity: 2,
      purchasePrice: 680,
      salePrice: 2000,
    },
    {
      code: "0068",
      name: "3.0 Quick Car Charger Round Lott",
      quantity: 1,
      purchasePrice: 240,
      salePrice: 630,
    },
    {
      code: "0069",
      name: "Silicon Suction Car Stand",
      quantity: 1,
      purchasePrice: 210,
      salePrice: 600,
    },
    {
      code: "0070",
      name: "Battery Clip Charger telelink",
      quantity: 1,
      purchasePrice: 210,
      salePrice: 550,
    },
    {
      code: "0071",
      name: "Samsung Type-C Fast Cable",
      quantity: 5,
      purchasePrice: 90,
      salePrice: 450,
    },
    {
      code: "0072",
      name: "Crown 10+1 Ultra Watch with earbuds",
      quantity: 2,
      purchasePrice: 2000,
      salePrice: 3550,
    },
    {
      code: "0073",
      name: "K8 Single Wireless Mic",
      quantity: 1,
      purchasePrice: 850,
      salePrice: 1850,
    },
    {
      code: "0074",
      name: "iPhone X Max Adapter 1A",
      quantity: 3,
      purchasePrice: 260,
      salePrice: 670,
    },
    {
      code: "0075",
      name: "MicroUSB to Type-C Charging OTG",
      quantity: 10,
      purchasePrice: 60,
      salePrice: 450,
    },

    {
      code: "0076",
      name: "100W Charger Flash VOOC Super Fast",
      quantity: 1,
      purchasePrice: 650,
      salePrice: 1450,
    },
    {
      code: "0077",
      name: "JBL M3 Mini Simple speaker",
      quantity: 1,
      purchasePrice: 650,
      salePrice: 1250,
    },
    {
      code: "0078",
      name: "Bareek Pin Patta",
      quantity: 10,
      purchasePrice: 12,
      salePrice: 100,
    },
    {
      code: "0080",
      name: "Lazy Snake Stand",
      quantity: 2,
      purchasePrice: 420,
      salePrice: 950,
    },
    {
      code: "0081",
      name: "Type-C 2-1 Converter White all models",
      quantity: 2,
      purchasePrice: 380,
      salePrice: 850,
    },
    {
      code: "0082",
      name: "ANC pro 2 wireless earbuds headphones",
      quantity: 2,
      purchasePrice: 1600,
      salePrice: 3750,
    },
    {
      code: "0083",
      name: "ANC pro 2 wireless earbuds headphones copy",
      quantity: 2,
      purchasePrice: 750,
      salePrice: 2350,
    },
    {
      code: "0084",
      name: "Air 31 wireless earbuds headphones with pouch cover",
      quantity: 2,
      purchasePrice: 600,
      salePrice: 1350,
    },
    {
      code: "0085",
      name: "OG Glass VIVO Y20",
      quantity: 50,
      purchasePrice: 58,
      salePrice: 250,
    },
    {
      code: "0086",
      name: "OG Glass VIVO S1",
      quantity: 20,
      purchasePrice: 58,
      salePrice: 250,
    },
    {
      code: "0087",
      name: "OG Glass Redmi 13C",
      quantity: 20,
      purchasePrice: 58,
      salePrice: 250,
    },
    {
      code: "0088",
      name: "OG Glass Infinix Smart 8",
      quantity: 20,
      purchasePrice: 58,
      salePrice: 250,
    },
    {
      code: "0089",
      name: "OG Glass Techno Cammon 30",
      quantity: 20,
      purchasePrice: 58,
      salePrice: 250,
    },
    {
      code: "0090",
      name: "OG Glass Samsung A10",
      quantity: 20,
      purchasePrice: 58,
      salePrice: 250,
    },
    {
      code: "0091",
      name: "OG Glass OPPO A1K",
      quantity: 20,
      purchasePrice: 58,
      salePrice: 250,
    },
    {
      code: "0092",
      name: "OG Glass Samsung A51",
      quantity: 20,
      purchasePrice: 58,
      salePrice: 250,
    },
    {
      code: "0093",
      name: "OG Glass Infinix Note 7",
      quantity: 20,
      purchasePrice: 58,
      salePrice: 250,
    },
    {
      code: "0094",
      name: "OG Glass iPhone 11 pro max",
      quantity: 10,
      purchasePrice: 58,
      salePrice: 250,
    },
    {
      code: "0095",
      name: "OG Glass iPhone 12 pro max",
      quantity: 10,
      purchasePrice: 58,
      salePrice: 250,
    },
    {
      code: "0096",
      name: "OG Glass iPhone 13 pro max",
      quantity: 10,
      purchasePrice: 58,
      salePrice: 250,
    },
    {
      code: "0094",
      name: "OG Glass iPhone 14 & 15 pro max",
      quantity: 10,
      purchasePrice: 58,
      salePrice: 250,
    },
    {
      code: "0095",
      name: "9D Glass VIVO S1",
      quantity: 10,
      purchasePrice: 32,
      salePrice: 100,
    },
    {
      code: "0096",
      name: "9D Glass Redmi 13C",
      quantity: 20,
      purchasePrice: 32,
      salePrice: 100,
    },
    {
      code: "0097",
      name: "9D Glass Infinix Smart 8",
      quantity: 10,
      purchasePrice: 32,
      salePrice: 100,
    },
    {
      code: "0098",
      name: "9d Glass Infinix Hot 9 Play",
      quantity: 10,
      purchasePrice: 32,
      salePrice: 100,
    },
    {
      code: "0099",
      name: "9D Glass Samsung A10",
      quantity: 10,
      purchasePrice: 32,
      salePrice: 100,
    },
    {
      code: "0100",
      name: "9D Glass HOT 10",
      quantity: 10,
      purchasePrice: 32,
      salePrice: 100,
    },
    {
      code: "0101",
      name: "9D Glass Samsung A51",
      quantity: 10,
      purchasePrice: 32,
      salePrice: 100,
    },
    {
      code: "0102",
      name: "9D Glass Infinix Note 7",
      quantity: 10,
      purchasePrice: 32,
      salePrice: 100,
    },
    {
      code: "0103",
      name: "9D Glass Vivo y20",
      quantity: 25,
      purchasePrice: 32,
      salePrice: 100,
    },
    {
      code: "0114",
      name: "OG Glass Samsung A15",
      quantity: 10,
      purchasePrice: 62,
      salePrice: 250,
    },
    {
      code: "0115",
      name: "OG Glass Samsung A70",
      quantity: 10,
      purchasePrice: 62,
      salePrice: 250,
    },
    {
      code: "0116",
      name: "OG Glass Infinix Note 12",
      quantity: 10,
      purchasePrice: 62,
      salePrice: 250,
    },
    {
      code: "0117",
      name: "OG Glass Vivo Y21E",
      quantity: 10,
      purchasePrice: 62,
      salePrice: 250,
    },
    {
      code: "0118",
      name: "OG Glass Infinix Hot 9 play",
      quantity: 10,
      purchasePrice: 62,
      salePrice: 250,
    },
    {
      code: "0119",
      name: "Infinix mobile Hot 50 android phone 8/128 Sicotel/green",
      quantity: 1,
      purchasePrice: 36600,
      salePrice: 40000,
    },
    {
      code: "0120",
      name: "Infinix mobile Hot 50i android phone 6/128 Sicotel/gray",
      quantity: 1,
      purchasePrice: 28600,
      salePrice: 33000,
    },
    {
      code: "0121",
      name: "Infinix mobile smart 9 android phone 4/128 Sicotel/black",
      quantity: 1,
      purchasePrice: 25500,
      salePrice: 29000,
    },
    {
      code: "0122",
      name: "Infinix mobile smart 9 android phone 4/128 Sicotel/gold",
      quantity: 1,
      purchasePrice: 25500,
      salePrice: 29000,
    },
    {
      code: "0123",
      name: "Infinix mobile smart 9 android phone 4/64 Sicotel/black",
      quantity: 2,
      purchasePrice: 22500,
      salePrice: 26000,
    },
    {
      code: "0124",
      name: "Infinix mobile smart 9 android phone 4/64 Sicotel/green",
      quantity: 2,
      purchasePrice: 22500,
      salePrice: 26000,
    },
    {
      code: "0125",
      name: "VIVO S1 Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0126",
      name: "VIVO S1 China Case",
      quantity: 1,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0127",
      name: "VIVO Y15 Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0128",
      name: "VIVO Y15S Lady Case",
      quantity: 5,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0129",
      name: "VIVO Y15S Bubble Case",
      quantity: 2,
      purchasePrice: 160,
      salePrice: 450,
    },
    {
      code: "0130",
      name: "VIVO Y17S Lady Case",
      quantity: 4,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0131",
      name: "VIVO Y17S China Case",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0132",
      name: "VIVO Y17S Leather Case",
      quantity: 1,
      purchasePrice: 100,
      salePrice: 300,
    },
    {
      code: "0133",
      name: "VIVO Y18 Lady Case",
      quantity: 2,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0134",
      name: "VIVO Y18 China Case",
      quantity: 3,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0135",
      name: "VIVO Y18 Chrom Case",
      quantity: 5,
      purchasePrice: 120,
      salePrice: 350,
    },
    {
      code: "0136",
      name: "VIVO Y18 Polo Case",
      quantity: 2,
      purchasePrice: 250,
      salePrice: 600,
    },
    {
      code: "0137",
      name: "VIVO Y19S Bubble Case",
      quantity: 3,
      purchasePrice: 160,
      salePrice: 450,
    },
    {
      code: "0138",
      name: "VIVO Y20 Lady Case",
      quantity: 11,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0139",
      name: "VIVO Y20 China Case",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0140",
      name: "VIVO Y21A Lady Case",
      quantity: 5,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0141",
      name: "VIVO Y21A China Case",
      quantity: 1,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0142",
      name: "VIVO Y21A Leather Case",
      quantity: 3,
      purchasePrice: 100,
      salePrice: 300,
    },
    {
      code: "0143",
      name: "VIVO Y21A Chrom Case",
      quantity: 2,
      purchasePrice: 120,
      salePrice: 350,
    },
    {
      code: "0144",
      name: "VIVO Y28 Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0145",
      name: "VIVO Y28 Bubble Case",
      quantity: 4,
      purchasePrice: 160,
      salePrice: 450,
    },
    {
      code: "0146",
      name: "VIVO Y03T China Case",
      quantity: 3,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0147",
      name: "VIVO Y36 China Case",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0148",
      name: "VIVO Y100 China Case",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0149",
      name: "VIVO V30E Chrom Case",
      quantity: 3,
      purchasePrice: 120,
      salePrice: 350,
    },
    {
      code: "0150",
      name: "VIVO V40 China Case",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0151",
      name: "OPPO A1K & C2 Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0152",
      name: "OPPO A3S Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0153",
      name: "OPPO A5S Lady Case",
      quantity: 2,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0154",
      name: "OPPO A5S China Case",
      quantity: 1,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0155",
      name: "OPPO A5S Chrom Case",
      quantity: 2,
      purchasePrice: 120,
      salePrice: 350,
    },
    {
      code: "0156",
      name: "OPPO A15 Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0157",
      name: "OPPO A16K Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0158",
      name: "OPPO A16K China Case",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0159",
      name: "OPPO A3 & A3X Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0160",
      name: "OPPO A3 & A3X China Case",
      quantity: 6,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0161",
      name: "OPPO A37 Chrom Case",
      quantity: 3,
      purchasePrice: 120,
      salePrice: 350,
    },
    {
      code: "0162",
      name: "OPPO A54 Lady Case",
      quantity: 2,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0163",
      name: "OPPO A60 China Case",
      quantity: 3,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0164",
      name: "REDMI A1+ Lady Case",
      quantity: 5,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0165",
      name: "REDMI A3 Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0166",
      name: "REDMI 13C Lady Case",
      quantity: 1,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0167",
      name: "REDMI 13C China Case",
      quantity: 3,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0168",
      name: "REDMI 13C Bubble Case",
      quantity: 2,
      purchasePrice: 160,
      salePrice: 450,
    },
    {
      code: "0169",
      name: "REDMI 14C Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0170",
      name: "REDMI 14C China Case",
      quantity: 9,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0171",
      name: "REDMI NOTE 12 Leather Case",
      quantity: 3,
      purchasePrice: 100,
      salePrice: 300,
    },
    {
      code: "0172",
      name: "INFINIX HOT 8 Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0173",
      name: "INFINIX HOT 8 China Case",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0174",
      name: "INFINIX HOT 9PLAY Lady Case",
      quantity: 6,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0175",
      name: "INFINIX HOT 10 Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0176",
      name: "INFINIX HOT 10 Chrom Case",
      quantity: 2,
      purchasePrice: 120,
      salePrice: 350,
    },
    {
      code: "0177",
      name: "INFINIX HOT 10PLAY Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0178",
      name: "INFINIX HOT 40 Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0179",
      name: "INFINIX HOT 40 Chrom Case",
      quantity: 2,
      purchasePrice: 120,
      salePrice: 350,
    },
    {
      code: "0180",
      name: "INFINIX HOT 40I Lady Case",
      quantity: 4,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0181",
      name: "INFINIX HOT 50 China Case",
      quantity: 7,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0182",
      name: "INFINIX HOT 50PRO China Case",
      quantity: 5,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0183",
      name: "INFINIX HOT 50PRO Bubble Case",
      quantity: 2,
      purchasePrice: 160,
      salePrice: 450,
    },
    {
      code: "0184",
      name: "INFINIX HOT50I China Case",
      quantity: 6,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0185",
      name: "INFINIX HOT 50PRO+ China Case",
      quantity: 3,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0186",
      name: "INFINIX SMART 5 Lady Case",
      quantity: 2,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0187",
      name: "INFINIX SMART 5 China Case",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0188",
      name: "INFINIX SMART7 Lady Case",
      quantity: 2,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0189",
      name: "INFINIX SMART7 China Case",
      quantity: 4,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0190",
      name: "INFINIX SMART 8 Lady Case",
      quantity: 8,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0191",
      name: "INFINIX SMART 8 China Case",
      quantity: 3,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0192",
      name: "INFINIX SMART 8 Bubble Case",
      quantity: 3,
      purchasePrice: 160,
      salePrice: 450,
    },
    {
      code: "0193",
      name: "INFINIX SMART 8 Chrom Case",
      quantity: 2,
      purchasePrice: 120,
      salePrice: 350,
    },
    {
      code: "0194",
      name: "INFINIX SMART 8 Polo Case",
      quantity: 2,
      purchasePrice: 250,
      salePrice: 600,
    },
    {
      code: "0195",
      name: "INFINIX SMART 9 China Case",
      quantity: 3,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0196",
      name: "INFINIX SMART 9 Bubble Case",
      quantity: 2,
      purchasePrice: 160,
      salePrice: 450,
    },
    {
      code: "0197",
      name: "INFINIX ZERO 40 China Case",
      quantity: 3,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0198",
      name: "INFINIX NOTE 40 Lady Case",
      quantity: 2,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0199",
      name: "TECNO Spark 6Go Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0200",
      name: "TECNO Spark Go 2023 Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0201",
      name: "TECNO SPARK GO 1 China Case",
      quantity: 9,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0202",
      name: "TECNO SPARK 20PRO+ Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0203",
      name: "TECNO SPARK 20PRO+ China Case",
      quantity: 1,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0204",
      name: "TECNO CAMMON 20 Lady Case",
      quantity: 4,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0205",
      name: "TECNO CAMMON 20 China Case",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0206",
      name: "TECNO CAMMON 30S China Case",
      quantity: 3,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0207",
      name: "TECNO CAMMON 30S Polo Case",
      quantity: 3,
      purchasePrice: 250,
      salePrice: 600,
    },
    {
      code: "0208",
      name: "TECNO SPARK 30PRO China Case",
      quantity: 3,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0209",
      name: "TECNO SPARK 30PRO Polo Case",
      quantity: 1,
      purchasePrice: 250,
      salePrice: 600,
    },
    {
      code: "0210",
      name: "REALME C51 C53 Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0211",
      name: "REALME C51 C53 Chrom Case",
      quantity: 3,
      purchasePrice: 120,
      salePrice: 350,
    },
    {
      code: "0212",
      name: "REALME C61 C63 China Case",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0213",
      name: "REALME C61 C63 Chrom Case",
      quantity: 2,
      purchasePrice: 120,
      salePrice: 350,
    },
    {
      code: "0214",
      name: "REALME NOTE 60 China Case",
      quantity: 5,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0215",
      name: "REALME NOTE 60 Chrom Case",
      quantity: 3,
      purchasePrice: 120,
      salePrice: 350,
    },
    {
      code: "0216",
      name: "SAMSUNG A04S China Case",
      quantity: 3,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0217",
      name: "SAMSUNG A05S Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0218",
      name: "SAMSUNG A05 China Case",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0219",
      name: "SAMSUNG A05 Chrom Case",
      quantity: 2,
      purchasePrice: 120,
      salePrice: 350,
    },
    {
      code: "0220",
      name: "SAMSUNG A06 Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0221",
      name: "SAMSUNG A06 Chrom Case",
      quantity: 3,
      purchasePrice: 120,
      salePrice: 350,
    },
    {
      code: "0222",
      name: "SAMSUNG A12 Lady Case",
      quantity: 1,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0223",
      name: "SAMSUNG A14 Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0224",
      name: "SAMSUNG A15 Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0225",
      name: "SAMSUNG A15 Bubble Case",
      quantity: 2,
      purchasePrice: 160,
      salePrice: 450,
    },
    {
      code: "0226",
      name: "SAMSUNG A16 China Case",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0227",
      name: "SAMSUNG A20 Lady Case",
      quantity: 3,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0228",
      name: "SAMSUNG A24 Lady Case",
      quantity: 2,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0229",
      name: "SAMSUNG A32 Lady Case",
      quantity: 4,
      purchasePrice: 210,
      salePrice: 500,
    },
    {
      code: "0230",
      name: "SAMSUNG A32 Bubble Case",
      quantity: 3,
      purchasePrice: 160,
      salePrice: 450,
    },
    {
      code: "0231",
      name: "TPU C51/C53",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0232",
      name: "TPU REDMI 13C",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0233",
      name: "TPU REDMI A3",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0234",
      name: "TPU REDMI 14C",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0235",
      name: "TPU INF HOT 30pPLAY",
      quantity: 3,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0236",
      name: "TPU CAMMON 20",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0237",
      name: "TPU SMART 8",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0238",
      name: "TPU VIVO Y85",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0239",
      name: "TPU Y33S",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0240",
      name: "TPU Y12/Y15",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0241",
      name: "TPU Y17S",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0242",
      name: "TPU OPPO A3X",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0243",
      name: "TPU SAM A05",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0244",
      name: "TPU SAM 06",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0245",
      name: "TPU SAM A14",
      quantity: 2,
      purchasePrice: 170,
      salePrice: 400,
    },
    {
      code: "0246",
      name: "Samsung mobile Reno f12 8/256",
      quantity: 1,
      purchasePrice: 55500,
      salePrice: 60200,
    },
    {
      code: "0247",
      name: "7+1 Watch / Straps Chain Orange",
      quantity: 1,
      purchasePrice: 1350,
      salePrice: 2650,
    },
    {
      code: "0248",
      name: "Cutter",
      quantity: 1,
      purchasePrice: 350,
      salePrice: 1000,
    },
    {
      code: "0249",
      name: "forward cutting machine",
      quantity: 1,
      purchasePrice: 105000,
      salePrice: 120000,
    },
  ],
};

module.exports = data;
